name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  black:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install the dependency manager
        run: pip install poetry
      - name: Install the project dependencies
        run: poetry install
      - name: Run the linter
        run: poetry run python -m black tap_strava --check --diff --color